# Generated by Django 3.2.5 on 2021-08-23 22:11

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('sub_title', models.TextField(verbose_name='العنوان الفرعي')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='المقال')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique_for_date='publish')),
                ('picture', models.ImageField(blank=True, default='default/default_post.jpg', upload_to='post_pics', verbose_name='خلفية')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='كتب في ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='عدل في')),
                ('status', models.CharField(choices=[('DRA', 'غير مكتمل'), ('PUB', 'نشر')], default='DRA', max_length=3, verbose_name='الحالة')),
                ('active', models.BooleanField(default=True, verbose_name=' مفعل')),
                ('total_likes_f', models.IntegerField(default=0)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('saved', models.ManyToManyField(blank=True, related_name='saved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=200, verbose_name='Tag')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='كتب في ')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500, verbose_name='تعليق')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='كتب في ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='عدل في')),
                ('active', models.BooleanField(default=True, verbose_name=' مفعل')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.article')),
                ('comment_likes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='posts.Tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL),
        ),
    ]
