# Generated by Django 3.2 on 2021-04-10 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import profiles.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=7, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=254, verbose_name='Username')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('checked', models.BooleanField(default=False, verbose_name='Checked')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(editable=False, null=True)),
                ('first_ip', models.GenericIPAddressField(editable=False, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='البلد')),
                ('bio', models.TextField(blank=True, verbose_name='المواصفات الشخصية')),
                ('super_profile', models.BooleanField(default=False)),
                ('photo', models.ImageField(default='default/default_profile.jpg', upload_to=profiles.models.img_func_profile, verbose_name='صورة')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='كتب في ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='عدل في')),
                ('website', models.URLField(blank=True, verbose_name='موقع إلكتوني')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
