# Generated by Django 3.2.5 on 2021-08-28 09:54

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default/default_profile.png', upload_to=profiles.models.img_func_profile, verbose_name='صورة'),
        ),
    ]
